---
configure_dock: true
dockitems_remove: []
#  - 'App Store'
#  - Podcasts
#  - Siri
#  - TV
dockitems_persist: []


configure_dotfiles: true
dotfiles_repo: 'https://github.com/rkrieger/dotfiles.git'
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "~/Documents/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .aliases
  - .zshrc


homebrew_installed_packages:
  - ansible
  - ansible-lint
  - asciinema
  - bgpq4
  - gh
  - gnupg
  - grepcidr
  - hcloud
  - hugo
  - ipmitool
  - kubernetes-cli
  - libyubikey
  - mg
  - mtr
  - node@20
  - pinentry
  - pinentry-mac
  - pngpaste
  - podman
  - python@3.12
  - virtualenv
  - tmux
  - vultr
  - wget
  - yamllint
  - youtube-dl
  - zeromq

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - drawio
  - firefox@esr
  - google-drive
  - google-chrome
  - handbrake
  - keepassxc
  - keybase
  - licecap
  - orange
  - pgadmin4
  - powershell
  - remarkable
  - scroll-reverser
  - signal
  - spotify
  - stack
  - telegram
  - utm
  - visual-studio-code
  - vlc
  - whatsapp
  - winbox
  - wireshark


mas_installed_apps:
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 1451685025, name: "Wireguard" }
  - { id: 413857545,  name: "Divvy" }
  - { id: 462058435,  name: "Microsoft Excel" }
  - { id: 462062816,  name: "Microsoft PowerPoint" }
  - { id: 784801555,  name: "Microsoft OneNote" }
  - { id: 462054704,  name: "Microsoft Word" }
  - { id: 409203825,  name: "Numbers" }
  - { id: 409183694,  name: "Keynote" }
  - { id: 409201541,  name: "Pages" }
  - { id: 406825478,  name: "Telephone" }
  - { id: 497799835,  name: "Xcode" }


configure_sshkey: true
sshkey_type: ed25519
sshkey_privkey: "id_{{ sshkey_type }}"
sshkey_pubkey: "{{ sshkey_privkey }}.pub"
sshkey_defpassphrase: ''
sshkey_user: "{{ [ ansible_user, username, lookup('env','USER'), ansible_facts['ansible_user_id'] ] | select('defined') | first }}"
sshkey_comment: "{{ sshkey_user }}@{{ ansible_hostname | lower }}"
