---
- name: Bootstrap macOS
  hosts: all
  vars_files:
    - default.config.yml


  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - import_tasks: tasks/pre_sshkey.yml
      when: configure_sshkey
      tags: ['sshkey']


  tasks:
    - import_tasks: tasks/sshkey.yml
      when: configure_sshkey
      tags: ['sshkey']
