---
- name: Bootstrap macOS
  hosts: all
  vars_files:
    - default.config.yml


  pre_tasks:
    - name: Include playbook configuration
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: SSH key auth prepared
      ansible.builtin.import_tasks:
        file: tasks/pre_sshkey.yml
      when: configure_sshkey
      tags: ['sshkey']


  roles:
    - role: geerlingguy.dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - name: SSH key auth configured
      ansible.builtin.import_tasks:
        file: tasks/sshkey.yml
      when: configure_sshkey
      tags: ['sshkey']
