---
- name: Bootstrap macOS
  hosts: all
  vars_files:
    - default.config.yml


  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - import_tasks: tasks/pre_sshkey.yml
      when: configure_sshkey
      tags: ['sshkey']


  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']


  tasks:
    - import_tasks: tasks/sshkey.yml
      when: configure_sshkey
      tags: ['sshkey']
