---
- name: Bootstrap macOS
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Check presence of SSH keypair
      stat:
        path: "~/.ssh/{{ sshkey_privkey }}"
      register: _sshkey_file
    - name: Get a password for the SSH keypair
      pause:
        prompt: "Enter a password for the SSH private key"
      register: _sshkey_prompt
      when:
        - not _sshkey_file.stat.exists
        - sshkey_passphrase is undefined

  tasks:
    - name: SSH keypair exists for user
      user:
        name: "{{ sshkey_user }}"
        generate_ssh_key: true
        ssh_key_type: "{{ sshkey_type }}"
        ssh_key_file: "~/.ssh/{{ sshkey_privkey }}"
        ssh_key_passphrase: "{{ _passphrase | select('defined') | first }}"
        ssh_key_comment: "{{ sshkey_comment }}"
      vars:
        _passphrase:
          - "{{ _sshkey_prompt.user_input is defined | ternary(_sshkey_prompt.user_input, undef) }}"
          - "{{ sshkey_passphrase is defined | ternary(sshkey_passphrase, undef )}}"
          - "{{ sshkey_defpassphrase }}"
      when:
        - configure_sshkey
        - not _sshkey_file.stat.exists
