---
- name: "SSH keypair exists for {{ sshkey_user }}"
  ansible.builtin.user:
    name: "{{ sshkey_user }}"
    generate_ssh_key: true
    ssh_key_type: "{{ sshkey_type }}"
    ssh_key_file: "~/.ssh/{{ sshkey_privkey }}"
    ssh_key_passphrase: "{{ _passphrase | select('defined') | first }}"
    ssh_key_comment: "{{ sshkey_comment }}"
  vars:
    _passphrase:
      - "{{ ansible.builtin.ternary(_sshkey_prompt.user_input, undef, omit) }}"
      - "{{ ansible.builtin.ternary(sshkey_passphrase, undef, omit) }}"
      - "{{ sshkey_defpassphrase }}"
  when:
    - not _sshkey_file.stat.exists
...
